export const AUTHENTICATED = "AUTHENTICATED";
export const GET_LOGGED_IN_USER = "GET_LOGGED_IN_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const IS_FETCHING = "IS_FETCHING";
export const DONE_FETCHING = "DONE_FETCHING";
export const USER_DETAIL = "USER_DETAIL";